### ISSUE TITLE
Make redistributable

### ISSUE THREAD

**Issue by simonbyrne** [simonbyrne/libcg#11]
In addition to #5, we would need a way to package up `libjulia` and any dependent libraries which are used (openblas?)

**Comment by KristofferC** [comment]
The `create_app` function in PackageCompiler does this. Also includes artifacts.

**Comment by simonbyrne** [comment]
> The `create_app` function in PackageCompiler does this. Also includes artifacts.

Can you specify your own `@ccallable`s with `create_app`? I couldn't see a way to do that.

**Comment by KristofferC** [comment]
You should  be able to just put them in the module that the app is created from.

**Comment by simonbyrne** [comment]
Is there a way to use `create_app` to just create a dynamic library? Or should we add a `create_library` to PackageCompiler.jl?

**Comment by KristofferC** [comment]
We could refactor things so that https://github.com/JuliaLang/PackageCompiler.jl/blob/1e611e47500e74915cd854f621929db03da34871/src/PackageCompiler.jl#L648-L649 does not get called. Then you would not end up with the executable. However, for artifacts to work we need to set the `DEPOT_PATH` somehow. This is currently done in `main` of the executable: https://github.com/JuliaLang/PackageCompiler.jl/blob/1e611e47500e74915cd854f621929db03da34871/src/embedding_wrapper.c#L42-L45 so some other way has to be figured out.

**Comment by kmsquire** [comment]
Hi, just curious if there has been any progress in this front?  If we wanted to help, is the previous message from @KristofferC the best way forward?

**Comment by simonbyrne** [comment]
No progress unfortunately, and I am not likely to have time to pursue this in the immediate future. I think the path @KristofferC suggested would probably be the best approach. I would be happy to review any contributions (or give you commit access if that is easier).

**Comment by kmsquire** [comment]
Closed by #18
